# NOTE: Generated By HttpRunner v3.1.5
# FROM: har\search.har
# 参数化驱动
# import self as self

import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, Parameters

# from config.ExcelUtiltest import ParseExcel


class TestCaseSearch(object):
    # 法一：@pytest.mark.parametrize(args_name, args_value)
    @pytest.mark.parametrize('args', ['y', 'z', 'q'])
    def test_api(self, args):
        print(args)

    '''
    config = Config("参数化搜索").verify(False)

    teststeps = [
        Step(
            RunRequest("搜索接口")
                .post("https://xxx.mand/web/v1/contract/page")
                .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "249",
                }
            )
                .with_json(
                {
                    "styleCode": "$styleCode",
                    "purchaserNameLike": "$purchaserNameLike",
                    "status": "",
                    "pageNum": 1,
                    "pageSize": 20,
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json")
                .assert_equal("body.successful", True)
                .assert_equal("body.code", "200")
                .assert_equal("body.message", "请求成功")
        ),
    ]
    '''


if __name__ == '__main__':
        pytest.main(['a_test.py'])